version: "2.0"
services:
  jenkins:
    build: ../files
    container_name: 'jenkins'
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./plugins:/var/jenkins_home/plugins
      - ./jenkinsConfig/jobs:/var/jenkins_home/jobs
      - ./jenkinsConfig/nodes:/var/jenkins_home/nodes
    networks:
      main:
networks:
  main:
